### ISSUE TITLE
Can't run your project

### ISSUE THREAD

**Issue by rajdeepratan** [eladnm/School-Management-System#1]
npm start is not working.

> npm ERR! Invalid name: "School management system"
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/superman/.npm/_logs/2018-09-17T11_18_44_365Z-debug.log
> Rajdeeps-MacBook-Pro:School-Management-System superman$ npm start
> npm ERR! Invalid name: "School management system"
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/superman/.npm/_logs/2018-09-17T11_24_06_827Z-debug.log
> Rajdeeps-MacBook-Pro:School-Management-System superman$ npm start
> npm ERR! Invalid name: "School management system"
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     /Users/superman/.npm/_logs/2018-09-17T11_25_37_363Z-debug.log

<img width="1022" alt="screen shot 2018-09-17 at 4 48 55 pm" src="https://user-images.githubusercontent.com/29138055/45620535-eab10600-ba9a-11e8-8e86-3b33c22cbef4.png">

**Comment by GraxMonzo** [comment]
omg just rename to School-Management-System

**Comment by AbhishekAnand01** [comment]
I have also faced  the same issue.

And as per convention we can not use UpperCase in name.
Example:
"name":"My Project"   --Wrong
"name":"My-Project"  --Right

I am able to solve the  issue by editing code mentioned below.
![image](https://user-images.githubusercontent.com/39114448/92225617-18c6c500-eec1-11ea-9999-043237a221ca.png)
